extends: default

ignore: |
  ansible/.ansible
  .venv
  .ansible
  terraform

rules:
  document-start: disable
  truthy: disable
  quoted-strings:
    quote-type: double
    required: only-when-needed
  line-length:
    max: 250
  comments-indentation:
    ignore: |
      ansible/host_files/docker01/docker-compose/authelia/config/configuration.yml
