---
name: Ansible Deploy Docker Compose

on:
  schedule:
    - cron: 0 7 * * *
  workflow_dispatch:

jobs:
  ansible:
    name: Ansible Docker Deploy
    runs-on: ubuntu-latest
    env:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ secrets.REPOSITORIES_TOKEN }}
          submodules: true

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: 3.14.3

      - uses: taiki-e/install-action@just

      - name: Ansible Setup
        run: just ansible-setup

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Ansible Deploy Docker
        run: just ansible-deploy --limit docker --tags docker-compose

      - name: Ansible Deploy Adguard Home
        run: just ansible-deploy --limit dns --tags adguardhome

      - name: Ansible Deploy traefik
        run: just ansible-deploy --limit proxy --tags traefik

      - name: Notify on Failure
        if: failure()
        uses: umahmood/pushover-actions@v1.1.0
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER_TOKEN }}
        with:
          status: ${{ job.status }}
          title: Ansible Deploy
          message: Ansible Deploy Pipeline Failed!
