---
name: Ansible Lint

on:
  pull_request:

jobs:
  ansible:
    name: Ansible Lint
    runs-on: ubuntu-latest
    env:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.REPOSITORIES_TOKEN }}
          submodules: true

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: 3.14.2

      - uses: taiki-e/install-action@just

      - name: Ansible Setup
        run: just ansible-setup

      - name: Ansible Lint
        run: just ansible-lint
