---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  dependsOn:
  - name: sealed-secrets
    namespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "v1.17.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-config
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: raw
      version: "v2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: flux-system
      interval: 12h
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  - name: sealed-secrets
    namespace: kube-system
  values:
    resources:
    - apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        name: cloudflare-dns
        namespace: cert-manager
      spec:
        encryptedData:
          cert-manager-access-token: AgCkhbVXj1uA1VUMTvNM9LDi43vW/rG4om4aMVL12HA2KXnrGSw88KuxI63HViTZSIkbVyVwTszOV3FBwrmsYAep+T+Ya9Pz5oEjVhZZd5e3n5XEn1rRNG7mPxscM26tuJa+JWQENpGU6c3wU6iiN6hyOxmj/LSBa78bHlinXjP4coW5Wi3FDDfH3PcrZPMhXYNw5w0kjKp2MP0TIqPwuHICvJeeX9J879H6Oo8yHgvx+Aa0+gjeObo2juEu3JK5Kpf0DXMY8dbSyo7TlxxoH+I/hEiZfXjDlPOH/Iea1S87I7mA49u3hyNvHRFfPCRON2RWhIjLAV6/EPHSm1RHna89X7Xvsg7W5WNjd6b+XKirim4iV+/QTyD2iTvCJTT9I2rGnL26+r+rGkqnAb1Hr65X2GYwpt3EojYFfhtBzE52qrzjs28T+dwm+QYAdXHi5M/z6ViQimm1APBXyweWfxl9MYzFuE4gPFbES1Cs8+PsnNFB98ZMZNspgZlNmfKnVbGe3ndVBk3UQZYYOChEi3zc0p7KS1DSpXlKzzL1D7DtM+RF5TX2T89omA7VJ3nbPj2yf+oYzA9cgge2sEjulB4YWODGSeP/eQ5DR7dOkcA15pwBhGXDQKeSaVIKZjFcOLret1swl75gBH2m7st+YG0XJMuHj2HZIl6sVxg0OyvxBcEr8cuvXtoYjz6vUbtgjd2+XhlfuyTVdyu+KbfKF66PuE10JFcNQh42eYqRgSFueSHWTZxBGoqO
        template:
          metadata:
            name: cloudflare-dns
            namespace: cert-manager

    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-prod
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-prod-private-key
          solvers:
            - dns01:
                cloudflare:
                  apiTokenSecretRef:
                    name: cloudflare-dns
                    key: cert-manager-access-token

    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-staging
      spec:
        acme:
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-staging-private-key
          solvers:
            - dns01:
                cloudflare:
                  apiTokenSecretRef:
                    name: cloudflare-dns
                    key: cert-manager-access-token
