---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb-config
  namespace: metallb
spec:
  interval: 30m
  chart:
    spec:
      chart: raw
      version: "v2.0.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: flux-system
      interval: 12h
  dependsOn:
  - name: metallb
    namespace: metallb
  values:
    resources: 
    - apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default-ipaddresspool
        namespace: metallb
      spec:
        addresses:
          - 192.168.1.230-192.168.1.240
    - apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: default-l2advertisement
        namespace: metallb
      spec:
        ipAddressPools:
          - default-ipaddresspool
