---
- name: Touch files
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: "0600"
    owner: root
    group: www-data
    access_time: preserve
    modification_time: preserve
  with_items: 
    - "{{ pve_storage_keys_path }}/{{ pve_storage_entry.name }}.pw"
    - "{{ pve_storage_keys_path }}/{{ pve_storage_entry.name }}.enc"
  when: pve_storage_entry.key is defined

- name: Create encryption key file
  ansible.builtin.copy:
    content: "{{ pve_storage_entry.key.enc }}"
    dest: "{{ pve_storage_keys_path }}/{{ pve_storage_entry.name }}.enc"
    mode: "0600"
    owner: root
    group: www-data
  when: pve_storage_entry.key is defined

- name: Create password key file
  ansible.builtin.copy:
    content: "{{ pve_storage_entry.key.pw }}"
    dest: "{{ pve_storage_keys_path }}/{{ pve_storage_entry.name }}.pw"
    mode: "0600"
    owner: root
    group: www-data
  when: pve_storage_entry.key is defined

- name: Add storage entry
  ansible.builtin.blockinfile:
    marker: "# {mark} {{ pve_storage_entry.name }}"
    path: "{{ pve_storage_file_path }}"
    prepend_newline: true
    block: |
      {{ pve_storage_entry.type }}: {{ pve_storage_entry.name }}
      {{ pve_storage_entry.attributes | indent( width=8, first=True ) }}
