---
apiVersion: source.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: 
      version: "0.13.7"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 12h
  values:
