---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgBOAQCwIODtV8IjbQKs4HebbKqRUZYdjUS0iLQeDdszY4iwN4Ydo2x27/wYHGusmbcioi0btfVlaDOgAqoLGCc3pCpK8Qi7NJ/Ejx7fshAQkoPO0cndPz1A8KMIdTKjQLcFU0fZwI8afydH/xl9KttF9C/GTyu/CQjRWRuZXBIBFDGbYL+bLL5Y66svI3/xsR5bQJCI/WfKZv29R1Fiy38zyCRNkW5Wvp9cv0f7yxIi65a8vi4BlymGit5mISfQ0G8SEY0od8Vz4ZueEulqJmKw4HCSRJH/5xGTpV5ihj22yGEpP2X0DvOsAhw4/8cUFq3TiBmOR1NlcZFwmoCIR3hAQ1Nokmp+fkj/Tk9uju4Hzmq5PT6T6jy84zObdZpm6xmzpv02aKc2WMUcSu1FC0xn4YKxC8A3bVNTUFJjYseIb0kt/K5WSTF2AhvificrxVC/Vv7F+Ap8bMgkU1At467w7C0vqVLMHJ7PBW6R1COXFAByH+v8MeWbtTmqmD3EGC5qR0TI4ISSMSbmwR68IMeAXU7LPdJ+bMHzW0QD53kVFBa4i+PbTBQ6xX8mNwqUc1Z2K3vJHwmthKTDaIHpWcEUd7Vctl088Ir9shtKJhGyWT3dB8UycjiMTmv0EOIR56tycjppQFyPT3sH2f5pMR08dSsdpof+XcdH/5++9XRJagzP7kTgOPB2hCLv4VPi3w7NWGqH+mLQ4NPkH8Uex0MHkMf0iuo8fsIPqZctnpvtzfrf94N9WjWfZKI3AQ==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: longhorn-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - longhorn.k8s.simn.io
      secretName: tls-longhorn
  rules:
  - host: longhorn.k8s.simn.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
