---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: adguard-configuration
  namespace: external-dns
spec:
  encryptedData:
    password: AgCRKiDmEDzotelu0g+3riHWDgmoDs/8/4Ue6JFN4LddgOQ1fwC1Q2uVbcyh05YsyGS027aCOczhBe+IlHTLtZimq6P9lDUYu9YKJ2DsrGGWmDjCRZcV0wujH9Abr+Llc0OjXquM81eFw1tPY41SsU/K5riYMDsSmBUt/fq5eutrdfWV3OYFiKgEAJejp1a5MVHixeKPxbCpHEftIPaaDzx1/49zkgEUWWIO3GO6lU0LFLkHhNYnjs92CwJ0TD5nmXYriYe02Oqwmzw9oGWENrzDIZors0LxqCr6LEeMjBFDQtz9xrrIkbWWwIyMAQPvyX6d34AN5z5FoZyLb426uDTt5KENB4F18S0sC4ydsc1FWBpgczL0blAlCpQNG4eWxGr215jkXWbs4O4GmkGWSmqtxiZ579+0VLEnHjSvw2EaRWFMu6fYhr6mqTeu5z//YqocaaWT/NCRvSRMLwBvn8zpjOVGlzT6eh1i6rOCZKweG3FAHQ4XxWQIQxwxCaQ/80Hl7w9CqRUvvRlPPZY9FSgDlOVVRYBIbqUjjNPqQVTU9s1VfNVPcT0kFvMkx2rpHMihkcUoeZM0YmsnrifypbyZCxhpWAxWaDHrTI3VRla4CI0PbTj2ft+ZDUdc4rISmjOyYhdR8yZYXAANzpXbXA8edJ4aklIEzS9Fed1agxjEoGiGeDj7xgA7p7LGq1fqpcFj8WodbvPFNqh+2juui4g3YOs=
    user: AgBy4Za9N8pbhyBb9/4anj3sLe9D0O5tbS6LLf9Q3mnZhd9rP451dJuRSZBmrEUB2Xc2daI1uW+TEYHC50gUsiA/Qc/+ZLi7VupvNz8FO1z28xq29jC5LyHwZjof7LJEJfOXhEOtEP0FmKrK0dxDZWACihpaVSAWCKstIgvDuFfFbeyeydzQ/kUI3j9SYbTFtwYua28wAF3qxIFMIA1Or7TQLC9BVjz+JDRZEPjzDmBsYfxhUqyG4ZZAmfkEKE9LHBHR9fv2qlefqxW5Mf8BpOZT2pASp8c5mcD7wcjcnbpwl5ctoDPkzTqBIQ3mCDoA5Bi/gq0pYeolPlurbzmQhEXkNFYUkqhi26jLktFnQLWtO5FTEkaHtV0Tg6C419m9/TdprHYk8D0m+qo+Am/16qWssz4j1DD7oNACarlw/vOKHicfNF2c7bBJT9QxkdLblgXP0wDvruoH0xcpoD+Hg8Q7s8edzj5MmnIDf3lFvXw2y5LGsD40M+uKmJKgxMYR1S3l6QAbnt9WikbNj4wKpecR6fCLE8Cg4VuPAsYbwgPBGAgR59e1rP9fDqDvvN0vldpmSUqlmu3t+wo5Jr3o4jk+QMzhIx2b7yO31E2SIjbVv0jTUL6Xe8MLlJtonTRNOr5nl9qsuL3Lhcu4V8w6ykCoRBdJAmdcF6Xm0WmQtGb5UxIwo+vtjy9KA/3Y7YBloPDPNLQxvg==
  template:
    metadata:
      creationTimestamp: null
      name: adguard-configuration
      namespace: external-dns
