---
- name: Create mount group
  ansible.builtin.group:
    name: "{{ cifs_mount_mount_group.name }}"
    state: present
    gid: "{{ cifs_mount_mount_group.id }}"
  become: true
  when: cifs_mount_mount_group.create

- name: Create mount user
  ansible.builtin.user:
    name: "{{ cifs_mount_mount_user.name }}"
    uid: "{{ cifs_mount_mount_user.id }}"
    group: "{{ cifs_mount_mount_group.name }}"
    create_home: false
  become: true
  when: cifs_mount_mount_user.create

- name: Create /mnt points
  ansible.builtin.file:
    dest: "{{ item.path }}"
    state: directory
    owner: "{{ cifs_mount_mount_user.id }}"
    group: "{{ cifs_mount_mount_group.id }}"
    mode: "0777"
  with_items:
    - "{{ cifs_mount_mount_mountpoints }}"

- name: Mount disks
  ansible.posix.mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    state: mounted
  with_items:
    - "{{ cifs_mount_mount_mountpoints }}"
