---
# simoncaron.pve_acme
pve_acme_domain: "{{ inventory_hostname }}.simn.io"

# geerlingguy.security
security_ssh_permit_root_login: "yes"
security_fail2ban_enabled: false

# geerlingguy.nut_client
nut_client_server: "192.168.1.100"

# network_configuration
network_configuration_interfaces:
  - device: "{{ ansible_cluster_network_device }}"
    auto: false
    method: manual
    family: inet

  - device: vmbr0
    auto: true
    method: static
    family: inet
    address: "{{ ansible_cluster_network_ip }}"
    gateway: "192.168.1.1"
    bridge:
      ports: "{{ ansible_cluster_network_device }}"
      stp: "off"
      fd: 0

  - device: "{{ ansible_storage_network_device }}"
    auto: false
    method: manual
    family: inet
    mtu: 9000

  - device: vmbr1
    auto: true
    method: static
    family: inet
    address: "{{ ansible_storage_network_ip }}"
    mtu: 9000
    bridge:
      ports: "{{ ansible_storage_network_device }}"
      stp: "off"
      fd: 0

# oefenweb.postfix
postfix_install:
  - libsasl2-modules

postfix_sasl_auth_enable: true
postfix_sasl_security_options: noanonymous, noplaintext
postfix_smtpd_tls_cert_file: /etc/ssl/certs

# buluma.cron
cron_jobs:
  - name: pve_host_backup_pbs01
    minute: "00"
    hour: "00"
    day: "*"
    month: "*"
    weekday: "*"
    job: >
      export PBS_REPOSITORY='{{ pbs01_repository }}';
      export PBS_PASSWORD='{{ pbs01_password }}';
      export PBS_ENCRYPTION_KEY_PATH='{{ pbs01_encryption_key_path }}';
      proxmox-backup-client login --repository $PBS_REPOSITORY;
      proxmox-backup-client backup pve.pxar:/etc/pve --repository $PBS_REPOSITORY --backup-id $(hostname) --keyfile $PBS_ENCRYPTION_KEY_PATH;
      unset PBS_REPOSITORY;
      unset PBS_PASSWORD;
      unset PBS_ENCRYPTION_KEY_PATH
    user: root

  - name: pve_host_backup_tuxis
    minute: "00"
    hour: "00"
    day: "*"
    month: "*"
    weekday: "0"
    job: >
      export PBS_REPOSITORY='{{ tuxis_repository }}';
      export PBS_PASSWORD='{{ tuxis_password }}';
      export PBS_ENCRYPTION_KEY_PATH='{{ tuxis_encryption_key_path }}';
      proxmox-backup-client login --repository $PBS_REPOSITORY;
      proxmox-backup-client backup pve.pxar:/etc/pve --repository $PBS_REPOSITORY --backup-id $(hostname) --keyfile $PBS_ENCRYPTION_KEY_PATH;
      unset PBS_REPOSITORY;
      unset PBS_PASSWORD;
      unset PBS_ENCRYPTION_KEY_PATH
    user: root
