# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/2 * * * *"

# runs the synchronisation on startup
runOnStart: true

# If enabled, the synchronisation task will not fail on single errors, but will log the errors and continue
continueOnError: true

origin:
  # url of the origin instance
  url: https://dns01.simn.io

# replicas instances
replicas:
  # url of the replica instance
  - url: https://dns02.simn.io

# Configure the sync API server, disabled if api port is 0
api:
  port: 0

# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true
