---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - proxmox-csi-plugin.yaml
  - bedag.yaml
  - metallb.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - sealed-secrets.yaml
  - external-dns.yaml
  - csi-driver-smb.yaml
  - spegel.yaml
