---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: multus-cni
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: 2.2.10
  url: oci://registry-1.docker.io/bitnamicharts/multus-cni
