---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: whereabouts
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: 1.2.9
  url: oci://registry-1.docker.io/bitnamicharts/whereabouts
