# bootstrap
bootstrap_extra_users:
  - name: plex
    uid: "10000"
    shell: /usr/sbin/nologin
    create_home: false

# geerlingguy.security
security_autoupdate_additional_origins:
  - site=downloads.plex.tv,archive=public,component=main
