---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ipaddresspool
  namespace: metallb
spec:
  addresses:
    - 192.168.1.250-192.168.1.255
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - default-ipaddresspool
