---
- name: Common Hosts Configurations
  hosts: all
  gather_facts: false
  roles:
    - role: bootstrap
    - role: ironicbadger.figurine
      become: true
    - role: geerlingguy.security
      become: true

- name: Proxmox Hosts Setup
  hosts: pve
  become: true
  roles:
    - network_configuration
    - simoncaron.pve_addons
    - simoncaron.pve_acme
    - geerlingguy.nut_client
    - oefenweb.postfix
