---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

docker01:
  host: docker01.simn.io
  port: 2375

docker02:
  host: docker02.simn.io
  port: 2375

monitoring01:
  host: monitoring01.simn.io
  port: 2375
