---
# artis3n.tailscale.machine
tailscale_args: --advertise-routes={{ pve_hosts.cidr_internal }}

# onkeldom.traefik
traefik_rules_config:
  - name: compress
    content:
      http:
        middlewares:
          compress:
            compress: {}

  - name: forwardauth
    content:
      http:
        middlewares:
          auth:
            forwardauth:
              address: http://docker01.simn.io:9091/api/verify?rd=https%3A%2F%2Fauth.simn.io%2F
              trustForwardHeader: true
              authResponseHeaders:
                - Remote-User
                - Remote-Groups
                - Remote-Name
                - Remote-Email
          securityHeaders:
            headers:
              customResponseHeaders:
                X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex
                server: ""
                X-Forwarded-Proto: https
              sslProxyHeaders:
                X-Forwarded-Proto: https
              referrerPolicy: same-origin
              hostsProxyHeaders:
                - X-Forwarded-Host
              customRequestHeaders:
                X-Forwarded-Proto: https
              contentTypeNosniff: true
              browserXssFilter: true
              forceSTSHeader: true
              stsIncludeSubdomains: true
              stsSeconds: 63072000
              stsPreload: true
          gzip:
            compress: {}

  - name: forgejo
    content:
      http:
        routers:
          router-forgejo:
            rule: Host(`git.simn.io`)
            service: service-forgejo
        services:
          service-forgejo:
            loadBalancer:
              servers:
                - url: http://forgejo01.simn.io:3000

  - name: nextcloud
    content:
      http:
        routers:
          nextcloud:
            rule: Host(`cloud.simn.io`)
            service: nextcloud
            middlewares:
              - nextcloud-chain
        services:
          nextcloud:
            loadBalancer:
              servers:
                - url: http://nextcloud01.simn.io:11000
        middlewares:
          nextcloud-secure-headers:
            headers:
              hostsProxyHeaders:
                - X-Forwarded-Host
              referrerPolicy: same-origin
          https-redirect:
            redirectscheme:
              scheme: https
          nextcloud-chain:
            chain:
              middlewares:
                - https-redirect
                - nextcloud-secure-headers

  - name: tdarr
    content:
      http:
        routers:
          tdarr:
            rule: Host(`tdarr.simn.io`)
            service: tdarr
            middlewares:
              - auth@file
        services:
          tdarr:
            loadBalancer:
              servers:
                - url: http://tdarr01.simn.io:8265

  - name: jellyfin
    content:
      http:
        routers:
          router-jellyfin:
            rule: Host(`jellyfin.simn.io`)
            service: service-jellyfin
        services:
          service-jellyfin:
            loadBalancer:
              servers:
                - url: http://jellyfin01.simn.io:8096
