---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config/whereabouts.cni.cncf.io_ippools.yaml
  - config/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  - daemonset.yaml
