---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: whereabouts
  namespace: flux-system
spec:
  interval: 24h
  ref:
    tag: 1.2.8
  url: oci://registry-1.docker.io/bitnamicharts/whereabouts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whereabouts
  namespace: kube-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: whereabouts
    namespace: flux-system
  values:
    tolerations:
      - operator: Exists
        effect: NoSchedule
